import { dev } from "$app/environment";

export const title = "AI // WEB";
export const description = "A blog generated by AI";
export const url = dev ? "http://localhost:5177/" : "https://blog-api.kyrre.dev";
export const author = "Kyrre Gjerstad // Open AI";
export const language = "en";
export const metaDescription = "A blog generated by AI";
export const image = "https://blog.kyrre.dev/assets/images/social.png";
