<script>
	import * as config from "$lib/config";
</script>

<svelte:head>
	<title>{config.title} | About</title>
</svelte:head>

<section>
	<h1>About Me</h1>
	<p>
		Hello and welcome to my blog! I'm Kyrre, a student at Noroff studying frontend development. This
		blog is a unique space where creativity meets technology. What sets this project apart is the
		synergy of human effort and artificial intelligence. Every blog post you read is entirely
		generated by OpenAI's GPT-4, and every image you see is generated by Midjourney.
	</p>

	<h2>The Journey and Collaboration</h2>

	<p>
		The blog's design is not just about showcasing my frontend development skills, but also about
		giving you, the reader, the power to customize your experience. On the side panel, you'll find
		options to apply your own color preferences and adjust the font size. Feel free to tweak these
		settings to create a reading experience that feels most comfortable and personal to you. One of
		the most exciting aspects of this blog is the ability to engage with the content. I invite you
		to leave a comment on each post. Every comment goes through a moderation process managed by
		ChatGPT, ensuring that our blog remains a safe and respectful space for all readers.
	</p>

	<h2>The Blog</h2>

	<p>
		In this blog, you'll find a wide array of topics that reflect the diverse capabilities of AI,
		ranging from web development tips and latest programming trends to UX/UI design insights. The
		blog also explores softer aspects of being a developer, such as the importance of perseverance,
		the thrill of lifelong learning, and the joy of problem-solving. Despite the AI-powered nature
		of the content, my aim has been to ensure that it remains accessible, informative, and
		inspiring. Whether you're a seasoned professional looking for a fresh perspective, a fellow
		student seeking guidance, or a curious individual eager to dive into the tech world, I hope
		you'll find something of interest here.
	</p>

	<h2>Final Words</h2>
	<p>
		So go ahead, make this blog your own, engage with the posts, and delve into the fascinating
		blend of technology and creativity that this space represents. I hope this blog not only
		narrates my journey but also becomes a part of your own exploration into the vast and exciting
		world of tech.
		<br />
		<br />
		Thank you for joining me on this exciting adventure.
	</p>

	<p>Kyrre</p>
</section>

<style>
	h1,
	h2 {
		font-size: var(--font-size-3XL, 1.875rem);
	}
	p {
		font-size: var(--font-size-M, 1rem);
		line-height: var(--line-height-default, 1.5);
		margin-bottom: 3rem;
	}
</style>
